### ISSUE TITLE
Healthcheck support

### ISSUE THREAD

**Issue by niemyjski** [conduktor/kafka-stack-docker-compose#110]
Would it be possible to add healthcheck support? I'm trying to run the single instance of zookeeper and kafka (`zk-single-kafka-single.yml`) on github actions. It seems like  it's not waiting for the kafka instance to be ready. I've also tried this and a bunch of other things:

```
    depends_on:
      kafka:
        condition: service_healthy
```

```yml
name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Start Services
      run: docker compose up -d && docker compose up ready || true
    - name: Verify
      run: docker run --network=host edenhill/kcat:1.7.1 -b localhost:9092 -L -T
  ```

The resulting output: https://github.com/FoundatioFx/Foundatio.Kafka/runs/6716787571?check_suite_focus=true
