### ISSUE TITLE
Unauthorized Schema Registry

### ISSUE THREAD

**Issue by BlankWheein** [conduktor/kafka-stack-docker-compose#128]
with this configuration of the Schema registry i can not connect to it using conduktor

```yml
kafka-schema-registry:
    image: confluentinc/cp-schema-registry:7.3.2
    hostname: kafka-schema-registry
    container_name: kafka-schema-registry
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      - kafka1
      - kafka2
      - kafka3
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka1:19092,PLAINTEXT://kafka2:19093,PLAINTEXT://kafka3:19094'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
```

i get the following error 
![image](https://user-images.githubusercontent.com/47646799/221972318-339b917c-06d7-45ba-b390-b53b8a902132.png)

I used the zk-multiple-kafka-mutltiple-schema-registry.yml file
i can connect to the clusters just fine, and it says it can connect to the schema registry just that i dont have the right authentication, any ideas on what i can do?
