### ISSUE TITLE
conduktor.yml - container name to conduktor-console

### ISSUE THREAD

**Issue by HaJunYoo** [conduktor/kafka-stack-docker-compose#142]
When I try to docker compose up with full-stack.yml, I keep getting an error saying `conduktor-platform` is missing, so when I looked at conduktor.yml

```
conduktor-console:
    image: conduktor/conduktor-console:1.21.0
    ports:
      - "8080:8080"
    volumes:
      - conduktor_data:/var/conduktor
    environment:

```

It wasn't `conduktor-platform` but `conduktor-console`! So in full-stack.yml's

```
conduktor-platform:
    extends:
      service: conduktor-platform
      file: conduktor.yml

```

If you change this part to

```
conduktor-console:
    extends:
      service: conduktor-console
      file: conduktor.yml

```

it works normally.
